title: Site
icon: 🤪

options:
  title: false
  duplicate: false
  status: false
  url: false
  delete: false


tabs:
  
  # Top Level Pages
  pageTab:
    label: Pages
    columns:
      - width: 1/2
        sections:
          top_pages:
            headline: Top Level Pages
            type: pages
            info: "{{ page.children.count }} children"
            layout: table
            image:
              cover: true
              ratio: 1/1
      - width: 1/2
        sections:
          hopper:
            type: pages
            headline: Submissions
            parent: site.find("submit")
            layout: cardlets  
  
  # Episode Pages
  episodeTab:
    label: F+ Episodes
    sections:
      episodes:
        extends: sections/episodePages
        status: listed
        layout: cards
        size: small
        limit: 49

  # Projects & Merch
  projectTab:
    label: Projects & Merch
    columns:
      - width: 1/2
        sections:
          projectItems:
            type: pages
            parent: site.find("also-made")
            template:
              - other-project
            layout: cardlets
            size: small
            sortBy: date desc
            sortable: false
      - width: 1/2
        sections:
          merchItems:
            type: pages
            parent: site.find("merch")
            template:
              - merch-type
              - stickers
            layout: cardlets
            size: small
            sortBy: date desc
            sortable: false

  # People
  peopleTab:
    label: People
    columns:
      - width: 1/1
        sections:
          ridiculists:
            type: pages
            parent: site.find("meet")
            layout: cardlets
            size: small
            sortBy: date desc
            sortable: false
            info: '<strong style="text-transform:capitalize">{{page.role}}</strong><br />{{page.job}}'
            limit: 40
  
  # People
  fanartTab:
    label: Fanart
    columns:
      - width: 1/1
        sections:
          fanartFiles:
            parent: site.find('fanart')
            label: Fanart Images
            type: files
            layout: cardlets
            template: fanimage